services:
  auth:
    build:
      context: ../../
      dockerfile: apps/auth/Dockerfile
    container_name: auth_service
    ports:
      - "${AUTH_PORT:-3001}:3001"
    env_file:
      - .env
      - ../../.env
    networks:
      - dexo_network
    restart: on-failure

networks:
  dexo_network:
    external: true
